### ISSUE TITLE
Choice of OPD map should be exposed to the user

### ISSUE THREAD

**Issue by kvangorkom** [kvangorkom/pandeia-coronagraphy#12]

**Comment by mperrin** [comment]
Copying from @kvangorkom's comment on #14:
> Can the pupil OPD be set via the JWInstruments.options dict? (It looks like it can't, but I could be wrong.) If so, this would address #12.

You're not wrong. Right now the OPD wants to be set by accessing the `.pupilopd` attribute directly, and there's no way to do it via the options dict.  However, the exact same fix would work for that - stay tuned...

**Comment by mperrin** [comment]
See PR #15 

not fully tested yet however..

**Comment by kvangorkom** [comment]
Closed by #15
