### ISSUE TITLE
LRU cache is incompatible with multiprocessing

### ISSUE THREAD

**Issue by kvangorkom** [kvangorkom/pandeia-coronagraphy#22]
The ```functools32.lru_cache``` decorator (currently decorating ```engine.get_psf_on_the_fly```) does not update the function cache when called on a separate process (as in when performing calculations with ```engine.calculate_batch```).

There are other caching implementations that appear to play nicely with multiprocessing, but that'd require adding a 3rd-party dependency, which I'd rather avoid. (Alternatively, I could roll my own, but that adds a failure mode I'd rather not deal with.)

**Comment by duhaime** [comment]
In case others arrive here, workers inside a multiprocessed function will update a `functools.lru_cache`, it's just that each worker gets their own cache.

To test this, we can create a list with 100 instances of 10 integers. Then we'll log each time each of these values is computed. We end up seeing that each value is computed only once for each processor on your machine:

```python
from multiprocessing import Pool
from functools import lru_cache

def a(i):
  return b(i)

@lru_cache(maxsize=50)
def b(j):
  print(' * computing', j)
  return j*2

l = []
for idx, i in enumerate(range(10)):
  for j in range(100):
    l.append(i)
print(l) # l contains 100 0's, 100 1's, ... 100 9's

p = Pool()
for i in p.imap(a, l):
  pass
```
