### ISSUE TITLE
which repo to use for future development? 

### ISSUE THREAD

**Issue by mperrin** [kvangorkom/pandeia-coronagraphy#33]
Hi @kjbrooks @kvangorkom - since @kvangorkom's no longer here at ST, do we have a transition plan for which repository to use for future development on this? I was just reminded by @abhijithrajan that I never made a PR for my version of this that re-enables the LRU caching for faster calculations. 

Should I submit that PR here, to @kjbrooks's fork of this repo, or somewhere else? Should we make a new fork of this inside the `spacetelescope` organization and declare that is the new primary master? I'm happy with whatever, just want to make sure that we all agree on the right path.

**Comment by kjbrooks** [comment]
My two cents is that we should go with the final option and make a new fork inside the `spacetelescope` organization and make it the new master. That should avoid any hand-off issues in the future, if they happen.

**Comment by mperrin** [comment]
That works for me. Do you know who we need to contact to set up a repo inside the `spacetelescope` organization?

**Comment by kjbrooks** [comment]
@mperrin I'm sending you an email with the contact information.

**Comment by kjbrooks** [comment]
We now have a new repo here: [https://github.com/spacetelescope/pandeia-coronagraphy](url).

**Comment by abhijithrajan** [comment]
moved the issue over to the new repo.​

**Comment by kjbrooks** [comment]
Thanks @abhijithrajan!

**Comment by mperrin** [comment]
I'm going to mark this issue as closed, because we've all agreed and the new repo is up and running. 

@kvangorkom, you might consider adding a note in the README here to point people towards the new repo? (at your discretion and as time permits in between school startup, of course. :-) )
